# Generated by Django 5.0.6 on 2024-06-16 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('BookUserId', models.SmallAutoField(primary_key=True, serialize=False)),
                ('BookUserName', models.CharField(help_text='Your username', max_length=64, verbose_name='Username')),
                ('BookUserEmail', models.EmailField(blank=True, help_text='Your username', max_length=64, null=True, verbose_name='Email')),
                ('BookUserGroup', models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Premium')], default=0, help_text='Your subscription plan', verbose_name='Subscription plan')),
                ('BookUserValidityDate', models.DateField(default=datetime.date(2026, 12, 31), help_text='Subscription is valid till this date', verbose_name='Expiration date')),
            ],
            options={
                'verbose_name': 'Book users',
                'ordering': ['BookUserGroup'],
            },
        ),
    ]
