# Generated by Django 5.0.6 on 2024-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='BookUserName',
            field=models.CharField(help_text='Your username', max_length=64, unique=True, verbose_name='Username'),
        ),
    ]
