# Generated by Django 5.0.6 on 2024-06-16 13:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='en', help_text='Main language used in the book', max_length=2, verbose_name='Language')),
                ('notes', models.TextField(blank=True, help_text='Like American Englis, Singlish,                              Simplified Chinese, Traditional Chinese, etc.', max_length=256, null=True, verbose_name='Special notes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='language_name_case_insensitive_unique', violation_error_message='Language already exists (case insensitive match)'),
        ),
    ]
