# Generated by Django 5.0.6 on 2024-06-17 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0002_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Main language used in the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_catalog.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text='Main language used in the book', max_length=200, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='notes',
            field=models.TextField(blank=True, help_text='Like American English, Singlish,                              Simplified Chinese, Traditional Chinese, etc.', max_length=256, null=True, verbose_name='Special notes'),
        ),
    ]
