# Generated by Django 5.0.6 on 2024-06-18 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0003_book_language_alter_language_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
