# Generated by Django 5.0.6 on 2024-06-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0004_alter_bookinstance_options_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
