# Generated by Django 5.0.6 on 2024-06-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0005_alter_bookinstance_id_alter_bookinstance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='id',
            new_name='instance_id',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
