# Generated by Django 5.0.6 on 2024-06-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0010_remove_bookinstance_instance_id_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
