# Generated by Django 5.0.6 on 2024-06-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0011_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name']},
        ),
    ]
