# Generated by Django 5.0.6 on 2024-06-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0012_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
