# Generated by Django 5.0.6 on 2024-06-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0014_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
