# Generated by Django 5.0.6 on 2024-06-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0015_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
